version: "3.9"

services:
  app:
    image: "ghcr.io/gabe565/ascii-movie"
    build:
      context: .
      target: debug
    environment:
      COLORTERM: "$COLORTERM"
      TERM: "$TERM"
    ports:
      - "23:23"
      - "2222:22"
